---
:bot:
  :server: 'netsplit.pirc.pl'
  :use_ssl: false
  :port: '6667'
  :channels:
  - '#s.m.s-testbot'
  :nick: 'm4ciu5_97'
  :realname: 'http://marahin.pl/'
  :user: 'macius'
:db:
  :server: ''
  :port:
  :user:
  :password:
  :database:
:plugins:
  - :file: 'admins.rb'
    :name: 'Admins'
  - :file: 'eval.rb'
    :name: 'AdminEval'
  - :file: 'joinpart.rb'
    :name: 'JoinPart'
  - :file: 'shortener.rb'
    :name: 'Gimbus'
  - :file: 'ipv6excuse.rb'
    :name: 'ipv6Excuse'
:plugins_path: 'plugins/'
:plugins_prefix: '^!'

:message_prefix: '→ '
